version: '3.1'

services:
    db:
        image: postgres:11
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: username
            POSTGRES_DB: test
        ports:
            - 5432:5432
